from bs4 import BeautifulSoup



# Provided string
html_string = '<div class="_s30J clearfix">NEW DELHI: The <a href="https://timesofindia.indiatimes.com/topic/bharatiya-janata-party" styleobj="[object Object]" class="" target="" frmappuse="1">BJP</a> on Sunday released its fifth list of 111 candidates for Lok Sabha elections.<br>The party has released the names of the candidates for the Lok Sabha seats of Uttar Pradesh, Bihar, Odisha, Rajasthan, Haryana, Maharashtra, West Bengal, Kerala, Karnataka, Goa, Gujarat, Himachal Pradesh, Jharkhand, Mizoram, Sikkim, Telangana, West Bengal and Andhra Pradesh.<div class="persObserver personaliseWidgetLoader_108753780 elU3m iTamo undefined" data-card="readAlso" data-heading="" data-section="India" data-subsection="" id="readAlso_108753780" data-msid="108753780" data-template="AS" data-contentprimestatus="non-prime" data-userprimestatus="non-prime" style="min-height:330.06px"></div><br>In its fifth list, BJP has named candidates for 111 more Lok Sabha seats including new joinee <!-- -->Naveen Jindal<!-- -->, actor <a href="https://timesofindia.indiatimes.com/topic/kangana-ranaut" styleobj="[object Object]" class="" target="" frmappuse="1">Kangana Ranaut</a> among nominees. Union minister Ashwini Choubey has been dropped from Buxar (Bihar); Sita Soren will contest from Dumka (Jharkhand).<br>Thanking the party after announcement, Kangana Ranaut said, "my beloved Bharat and Bhartiya Janta’s own party, Bharatiya Janta party (BJP) has always had my unconditional support, today the national leadership of BJP has announced me as their Loksabha candidate from my birth place Himachal Pradesh, Mandi (constituency) I abide by the high command’s decision on contesting <!-- -->Lok Sabha polls<!-- -->."<br><div class="mgid_second_mrec_parent"><div class="wdt-taboola" data-mode="thumbnails-mid" data-target_type="mix" style="max-height:415px;overflow:hidden" id="taboola-mid-article-thumbnails-108753780" data-placement="Mid Article Thumbnails 1"></div></div>"I feel honoured and elated to officially join the party. I look forward to be a worthy karyakarta and a reliable public servant," She added.<br>While Varun Gandhi has been dropped from Pilibhit, his mother Maneka Gandhi retained from Sultanpur. BJP has fielded Union minister Dharmendra Pradhan from Sambalpur and Sambit Patra from Puri. Actor Arun Govil, who played Ram in popular TV serial Ramayan, has been fielded by BJP from Meerut Lok Sabha seat.<div class="mgid_country_osv_parent"><div id="650c3bbfb55d271dc576e9c4-osv-mrec-108753780"></div></div><br>Jitin Prasada has replaced Varun Gandhi in Pilibhit. The party has also dropped ex-Union minister Anant Kumar Hegde from Uttara Kannada constituency.<br>In Bihar, the party has fielded Union ministers R.K Singh from Arrah, Nityanand Rai from Ujiarpur, and Giriraj Singh from Begusarai. Former Union ministers Ravi Shankar Prasad from Patna Sahib, Rajiv Pratap Rudy from Saran, Radha Mohan Singh from Purvi Champaran, and Ram Kripal Yadav from Pataliputra also in the</div>'

soup = BeautifulSoup(html_string, 'html.parser')

div_text = soup.find('div', class_='_s30J clearfix').get_text()

print(div_text)


